feature: correct counts for the search
devflowinc/trieve pull request #1050
Opened 2024-03-07 21:16 UTC by densumesh

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-03-08 19:34 UTC, skeptrunedev commented on server/src/operators/search_operator.rs
> +        / 10.0)
I think this should be `limit`

2024-03-08 19:35 UTC, skeptrunedev commented on server/src/operators/search_operator.rs
>      transaction.finish();
Should remove this

2024-03-08 19:35 UTC, skeptrunedev commented on server/src/operators/search_operator.rs
>          //FIXME: dont have total results now
Remove the `FIXME` comment

2024-03-08 19:35 UTC, skeptrunedev requested changes

2024-03-08 19:35 UTC, skeptrunedev commented on server/src/operators/search_operator.rs
> +        / 10.0)
Divide by `limit`

2024-03-08 19:35 UTC, skeptrunedev commented on server/src/operators/search_operator.rs
> +        / 10.0)
Divide by `limit`

2024-03-08 19:36 UTC, fastfists requested changes
Just add in the tracing for the function

2024-03-08 19:36 UTC, fastfists commented on server/src/operators/qdrant_operator.rs
> +
```suggestion
#[tracing::instrument]
```

2024-03-08 20:30 UTC, densumesh commented on server/src/operators/search_operator.rs
>      transaction.finish();
Remove which thing?

2024-03-09 01:36 UTC, skeptrunedev approved these changes

2024-03-09 04:13 UTC, merged