feature: migrate from redis to rabbitmq
devflowinc/trieve pull request #1146
Opened 2024-03-26 04:00 UTC by densumesh

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-03-26 04:07 UTC, fastfists commented on server/src/bin/ingestion-microservice.rs
>          .expect("Failed to fetch from redis pool");
```suggestion
        .expect("Failed to fetch from rabbit pool");
```

2024-03-26 04:09 UTC, fastfists commented on server/Cargo.toml
> +deadpool = "0.10.0"
```suggestion
```
Deadpool is not needed, deadpool_lapin replaces that

2024-03-26 04:10 UTC, fastfists commented on server/src/lib.rs
> +use deadpool_lapin::{Manager, Pool};
A bit of a nit but can these just be full scope pathed, we have so many Manager and Pool types that this could get confusing very fast

2024-03-26 04:11 UTC, fastfists commented on server/src/lib.rs
> +    let _ = channel
```suggestion
    channel
```
Let _ is only needed if you don't expect/unwrap/or return an error, in this case we expect so its not needed

2024-03-26 04:12 UTC, fastfists requested changes
A few nits, tried not to be too picky though

2024-03-30 16:40 UTC, skeptrunedev commented
Honestly seems like this would work and be better than Redis, but closing for now due to complication of extra infra for existing deployments.

2024-03-30 16:40 UTC, closed without merging