feat: save rag events to clickhouse
devflowinc/trieve pull request #1735
Opened 2024-07-02 22:03 UTC by drew-harris

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-07-02 22:22 UTC, drew-harris commented
Currently the chat website `llm_response` still contains all of the chunk information that gets cut by the "||". Lmk if you want me to cut it so that the response is just the "spoken" repsonse

2024-07-03 01:04 UTC, cdxker requested changes

2024-07-03 01:04 UTC, cdxker commented on server/src/handlers/analytics_handler.rs
> +        (status = 200, description = "RAG queries for the dataset", body = Vec<SearchLatencyGraph>),
```suggestion
        (status = 200, description = "RAG queries for the dataset", body = Vec<RagQueryEvent>),
```

2024-07-03 01:04 UTC, cdxker commented on server/src/handlers/analytics_handler.rs
> +            ServiceError::InternalServerError("Error fetching query".to_string())
Should we put this into an operator?

2024-07-03 01:13 UTC, merged