bugfix: selected org/dataset should be respected when navigating to playgrounds
devflowinc/trieve pull request #1782
Opened 2024-07-04 22:21 UTC by aaryanpunia

2024-07-04 22:59 UTC, skeptrunedev requested changes

2024-07-04 22:59 UTC, skeptrunedev commented on chat/src/components/contexts/UserContext.tsx
> +          console.log(data.orgs);
```suggestion
```

2024-07-04 23:20 UTC, aaryanpunia commented on chat/src/components/contexts/UserContext.tsx
> +          console.log(data.orgs);
fixed

2024-07-05 01:56 UTC, skeptrunedev approved these changes

2024-07-05 01:56 UTC, merged