feature: reorganize analytics site
devflowinc/trieve pull request #1850
Opened 2024-07-09 21:12 UTC by drew-harris

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-07-09 21:14 UTC, drew-harris commented
![image](https://github.com/devflowinc/trieve/assets/61394759/a12ca129-2c14-4338-89ba-06391febab87)

2024-07-09 21:14 UTC, drew-harris commented
![image](https://github.com/devflowinc/trieve/assets/61394759/2daa4436-f514-4e59-855e-efc5407581a3)

2024-07-11 16:47 UTC, densumesh commented
![image](https://github.com/devflowinc/trieve/assets/25559111/cd3f4d00-ba62-4695-8ce2-9af70bb496c8)
when theres a generate off chunks this seems to overflow

![image](https://github.com/devflowinc/trieve/assets/25559111/75c9ab04-957d-4bef-a05c-d99268264f11)
make this table wider

Should make a new issue to make the dedicated query page to view a single query and its results

2024-07-11 16:49 UTC, densumesh commented
![image](https://github.com/devflowinc/trieve/assets/25559111/26ff3cc4-69d7-4c91-b61f-27e4b115f048)

the bottom timestamps should correspond to the time range i.e. show the date rather than time stamp if looking at past week

Also if there is only 1 or 2 points make the graph have artifiically larger padding in terms of time so that the points aren't just at the side and are in the middle

2024-07-11 16:53 UTC, densumesh commented
![image](https://github.com/devflowinc/trieve/assets/25559111/180bbed0-2381-4c22-8df8-ab1ede53ada6)

Head queries should have a top bar showing what each row is as well

2024-07-11 18:33 UTC, drew-harris commented
Working now and bundle size is fixed. LGTM!

2024-07-11 21:13 UTC, densumesh requested changes

2024-07-11 21:13 UTC, densumesh commented on server/src/data/models.rs
> -        filter: Option<SearchAnalyticsFilter>,
This should remain the same no?

2024-07-11 21:59 UTC, densumesh approved these changes

2024-07-12 18:05 UTC, densumesh approved these changes

2024-07-12 18:05 UTC, merged