feature: make bm25 sparse vector
devflowinc/trieve pull request #1867
Opened 2024-07-11 02:55 UTC by cdxker

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-07-11 21:03 UTC, densumesh approved these changes

2024-07-11 21:20 UTC, skeptrunedev requested changes
BM25 should be active by default for a dataset. We should use default values for the constants instead. 

If someone in an org for a dataset does nothing then they should still get BM25.

2024-07-11 21:39 UTC, cdxker commented
Just updated it to on the search UI

2024-07-11 22:35 UTC, skeptrunedev requested changes
Add into `.env.search` for the `VITE_BM25_ACTIVE` env

2024-07-11 22:51 UTC, skeptrunedev requested changes

2024-07-11 22:51 UTC, skeptrunedev commented on .env.dashboard
> +VITE_BM25_ACTIVE=false
```suggestion
VITE_BM25_ACTIVE=true
```

2024-07-11 22:51 UTC, skeptrunedev commented on .env.search
> +VITE_BM25_ACTIVE=false
```suggestion
VITE_BM25_ACTIVE=true
```

2024-07-11 23:37 UTC, skeptrunedev requested changes
Need to have BM25 in update

2024-07-12 05:18 UTC, skeptrunedev approved these changes

2024-07-12 05:18 UTC, merged