feature: grpc with tei
devflowinc/trieve pull request #1957
Opened 2024-07-17 21:53 UTC by aaryanpunia

2024-07-22 18:07 UTC, cdxker requested changes
We may need to have a different strategy with how we will point to the other embedding servers. Maybe we just use the pre-existing env's `origin` env's and just swap if use_grpc is active?

2024-07-22 18:07 UTC, cdxker commented on server/src/operators/model_operator.rs
> +    let grpc_origin = get_env!("EMBEDDING_SERVER_GRPC_ORIGIN", "Grpc origin should be set");
How will this work with all the different types of embedding servers?

2024-07-22 18:07 UTC, cdxker commented on server/src/operators/model_operator.rs
> +    let grpc_origin = get_env!("EMBEDDING_SERVER_GRPC_ORIGIN", "Grpc origin should be set");
Remove `get_env!` and instead use `std::env::var()` since this is an optional parameter

2024-07-22 18:07 UTC, cdxker commented on server/src/operators/model_operator.rs
> +    let grpc_origin = get_env!("SPARSE_SERVER_GRPC_ORIGIN", "Grpc origin should be set");
Same as above, use std::env::var here instead

2024-07-22 18:07 UTC, cdxker commented on server/src/operators/model_operator.rs
> +    let grpc_origin = get_env!("RERANKER_SERVER_GRPC_ORIGIN", "Grpc origin should be set");
.

2024-07-22 18:07 UTC, cdxker commented on server/src/operators/model_operator.rs
> +    let grpc_origin = get_env!("SPARSE_SERVER_GRPC_ORIGIN", "Grpc origin should be set");
.

2024-07-22 18:07 UTC, cdxker commented on server/src/operators/model_operator.rs
> +    let grpc_origin = get_env!("SPARSE_SERVER_GRPC_ORIGIN", "Grpc origin should be set");
.

2024-07-22 18:10 UTC, cdxker commented
The testing needed for this is:

1) Start up the server without making any additional env changes and for the server to use http for embedding requests and ingestion messages.
2) Then add additional env's to have it point to grpc routes then rerun the same queries.

2024-07-23 23:51 UTC, aaryanpunia commented
Embedding calls are not being done in batches, getting batch size too large

2024-07-29 16:49 UTC, skeptrunedev commented
We **should** merge this PR, but we aren't going to right now because it seems complicated with helm for the services and the migration is intensive. There are other things higher in prio.

2024-07-29 16:49 UTC, closed without merging