feature: collapse search queries script
devflowinc/trieve pull request #1981
Opened 2024-07-19 22:28 UTC by aaryanpunia

2024-07-22 16:27 UTC, densumesh approved these changes

2024-07-22 16:28 UTC, densumesh requested changes

2024-07-22 16:28 UTC, densumesh commented on docker/collapse-query-script/Dockerfile
> +# Use an official Python runtime as a parent image
Create a CI action for building the docker image

2024-07-22 17:53 UTC, cdxker requested changes

2024-07-22 17:53 UTC, cdxker commented on .github/workflows/push-collapse-query-script.yml
> +            type=raw,latest
```suggestion
            type=raw,latest
            type=sha
```
Add this so we can tag the releases to the git commit

2024-07-22 18:32 UTC, cdxker approved these changes

2024-07-22 18:33 UTC, skeptrunedev requested changes
Add a README to `docker/collapse-query-script` which describes how this works 

I can't understand it just reading the code at glance

2024-07-22 19:59 UTC, skeptrunedev requested changes
README needs update to reflect time bound on collapse now

2024-07-22 22:02 UTC, skeptrunedev reviewed
Need to actually test this locally and make sure it works as expected then I think it's good to merge

2024-07-23 03:43 UTC, densumesh approved these changes

2024-07-23 03:44 UTC, merged