feature: api client package
devflowinc/trieve pull request #2134
Opened 2024-08-06 22:30 UTC by drew-harris

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-08-07 17:18 UTC, drew-harris commented
Fields are now renamed so that 
```ts
const test = await trieve.fetch("/api/chunk", "post", {
  datasetId: "c65a2dd7-298e-48e6-ac90-e336ccbbe74f",
  trDataset: "c65a2dd7-298e-48e6-ac90-e336ccbbe74f",
  requestBody: {
    chunk_html: "hello"
  }
});
```
becomes just
```ts
const test = await trieve.fetch("/api/chunk", "post", {
  datasetId: "c65a2dd7-298e-48e6-ac90-e336ccbbe74f",
  data: {
    chunk_html: "hello"
  }
});
```

2024-08-07 17:39 UTC, skeptrunedev requested changes
While I know that it breaks the turbo monorepo pattern. This new client should go into a folder called: 

`clients`

and then its own folder called `fetch-client`. 

Idea here is that we can add clients for other languages to the same folder.

2024-08-07 17:39 UTC, skeptrunedev commented on frontends/client/package.json
> +    "@hey-api/openapi-ts": "^0.48.2",
```suggestion
    "@hey-api/openapi-ts": "^0.52.1",
```

2024-08-07 17:39 UTC, skeptrunedev commented on frontends/client/package.json
> +    "esbuild": "^0.21.5",
```suggestion
    "esbuild": "^0.23.0",
```

2024-08-07 17:39 UTC, skeptrunedev commented on frontends/client/package.json
> +  "version": "0.0.1",
This should match the OpenAPI spec version

```suggestion
  "version": "0.11.7",
```

2024-08-15 03:35 UTC, cdxker approved these changes
Just reviewed locally, pretty happy with this. Going to make some issues for dog fooding the sdk from here.

2024-08-15 05:54 UTC, merged