feature: add dataset button to analytics
devflowinc/trieve pull request #2178
Opened 2024-08-13 20:07 UTC by vid277

![image](https://github.com/user-attachments/assets/b3b2019b-91e6-4ec4-8f16-76f204318e0e)

2024-08-13 20:12 UTC, drew-harris commented
I would move the dashboard icon to the bottom of that box to show that it's on a separate site. It looks like just another page on the analytics when its not.  Could also but a link to the api docs there too.

2024-08-13 20:13 UTC, drew-harris commented
Like here
![image](https://github.com/user-attachments/assets/b98d799e-7890-48ec-9c67-ce621c7a06ca)

2024-08-13 20:48 UTC, vid277 commented
![image](https://github.com/user-attachments/assets/c077e413-893c-41e3-b472-2aba8a3e921f)

2024-08-13 22:56 UTC, cdxker requested changes
One comment request and can you change the env name to `VITE_DASHBOARD_URL`, just to be consistent with how its named in the search ui and dashboard UI. Other than that it looks great!

2024-08-13 22:56 UTC, cdxker commented on .env.example
> +
```suggestion
```
These shouldn't be needed, as they are already defined in other locations.

2024-08-14 15:42 UTC, densumesh approved these changes

2024-08-14 15:42 UTC, merged