feat: add more links to analytics sidebar
devflowinc/trieve pull request #2268
Opened 2024-08-30 19:15 UTC by drew-harris

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-08-30 19:16 UTC, drew-harris commented
BEFORE:
![image](https://github.com/user-attachments/assets/5013c8a4-83d6-4c26-99c6-59584eeceffa)


AFTER:
![image](https://github.com/user-attachments/assets/29ed38a7-2cc2-4107-a170-bcced7145f66)

2024-08-30 21:41 UTC, skeptrunedev requested changes

2024-08-30 21:41 UTC, skeptrunedev commented on frontends/analytics/src/components/Sidebar.tsx
> +    icon: IoChatboxOutline,
These values should be env's and also link out to the playgrounds on the proper org and dataset similar to how dashboard links work. It's really disorienting when the link takes you to the wrong dataset.

2024-09-03 19:39 UTC, skeptrunedev approved these changes

2024-09-03 19:39 UTC, merged