faet: added more workers, moved ingest to the workers template
devflowinc/trieve pull request #2272
Opened 2024-08-30 21:46 UTC by cdxker

- **faet: added more workers, moved ingest to the workers template**
- **docs: added more instructions to testing locally**

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-08-31 02:18 UTC, pmig requested changes

2024-08-31 02:18 UTC, pmig commented on glasskube/trieve/cronjobs/clickhouse-collapse.yaml
> +  name: collapsing-queries-cron
most of the resources start with "trieve-". It might come in handy to also have these jobs follow the same naming convetions

2024-08-31 02:18 UTC, pmig commented on glasskube/trieve/cronjobs/cluster-queries.yaml
> +  name: cluster-queries-cronjob
```suggestion
  name: trieve-cluster-queries-cronjob
```

2024-08-31 02:18 UTC, pmig commented on glasskube/trieve/cronjobs/clickhouse-collapse.yaml
> +  name: collapsing-queries-cron
```suggestion
  name: trieve-collapsing-queries-cron
```

2024-08-31 02:18 UTC, pmig commented on glasskube/trieve/cronjobs/word-id-cronjob.yaml
> +    app.kubernetes.io/instance: {{ .Release.Name }}
```suggestion

```

2024-09-03 19:23 UTC, pmig approved these changes

2024-09-03 19:29 UTC, skeptrunedev approved these changes

2024-09-03 19:29 UTC, merged