feature: recognize domain specific words
devflowinc/trieve pull request #2273
Opened 2024-08-31 21:16 UTC by densumesh

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-09-01 22:07 UTC, skeptrunedev reviewed
Are the dependency removals here intentional?

2024-09-01 22:09 UTC, densumesh commented
> Are the dependency removals here intentional? 

Yes they are. No longer using bloom filters and bktree functions have been moved into our code

2024-09-01 22:15 UTC, skeptrunedev requested changes

2024-09-01 22:15 UTC, skeptrunedev commented on server/src/operators/typo_operator.rs
> +        let mut corrected_query = query.query.clone();
Behavior is correct, but it shouldn't always happen. `TypoOptions` needs another param, which defaults to True, such that the user can turn this behavior off if they want to.

2024-09-03 00:32 UTC, skeptrunedev requested changes
new request param needs to get added to options popover

2024-09-03 19:29 UTC, skeptrunedev approved these changes

2024-09-03 19:32 UTC, merged