feat: analytics on dashboard
devflowinc/trieve pull request #2395
Opened 2024-09-24 16:30 UTC by drew-harris

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-09-26 02:00 UTC, densumesh commented
![image](https://github.com/user-attachments/assets/ef0c83fa-5882-48ac-81d1-a40e8cc4449e)

2024-09-26 02:13 UTC, densumesh requested changes
need to add back button

2024-09-26 09:18 UTC, SaraVieira commented on frontends/dashboard/src/analytics/components/charts/NoResultQueries.tsx
>    console.log(notResultQuery.data);
console log left behind

2024-09-26 09:21 UTC, SaraVieira commented
Besides the back button mentioned the only think I have to add is that the button to open the analytics is still in the menu

Other than that this looks great!

2024-09-27 00:46 UTC, densumesh approved these changes

2024-09-27 00:49 UTC, merged