feature: mobile view for search component
devflowinc/trieve pull request #2449
Opened 2024-09-29 07:44 UTC by cdxker

- **feat: add chunk counts**
- **feat: create new toggle & delete custom item**
- **feat: move question to bottom && add suggested questions**
- **feat: add dark mode to new chat**
- **bugfix: avoid regen'ing suggestions immediately + refactor: chat even more chat-like**
- **feature: descending order messages and keep it on the same page**
- **feat: mobile view to be full screen**
- **cleanup: search component rag scroll bug fixed**

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-09-29 07:54 UTC, cdxker commented on clients/search-component/src/utils/hooks/useChat.ts
> +        }
Had to do a hack here to get the footer to be at the right position after a message is generated.

2024-09-29 19:16 UTC, skeptrunedev requested changes
Spacing between user and assistant blocks is off. They also need a border drawn between them.

2024-09-30 00:49 UTC, cdxker commented
![image](https://github.com/user-attachments/assets/7ddfb00e-28fc-47a4-ad13-fccfebe4f3f6)

Evened out the spacing.

2024-09-30 01:47 UTC, cdxker commented
![image](https://github.com/user-attachments/assets/540ffb1c-7ab4-40b9-bde6-d1044c2de42b)

Added vertical bars

2024-09-30 03:26 UTC, merged