Added All time
devflowinc/trieve pull request #3009
Opened 2024-12-25 02:01 UTC by ptdatta

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

Fixes #2986

2024-12-28 00:01 UTC, skeptrunedev requested changes
Granularity needs to change to `month`

2024-12-28 18:52 UTC, skeptrunedev requested changes
[Screencast from 12-28-2024 10:40:33 AM.webm](https://github.com/user-attachments/assets/3dae1e7a-6bfc-4e0f-8cff-649c3fc03694)

![image](https://github.com/user-attachments/assets/8f96f24a-9f64-41ff-91ff-c5c651000059)

There are some of functionality issues remaining with this PR.

- [ ] bugfix: I have to click on all time twice for it to take effect
- [ ] bugfix: granularity once all time takes effect is wrong
- [x] cleanup: last 7 days should also appear in calendar dropdown

2024-12-28 19:02 UTC, skeptrunedev commented
Also, please don't merge and only rebase. I took a few minutes to clean up the commits on this PR to be more inline with our syntax.

2024-12-29 03:57 UTC, ptdatta commented
> Also, please don't merge and only rebase. I took a few minutes to clean up the commits on this PR to be more inline with our syntax.

Sure, I created new branches for each of my PRs. Yes, this PR is not ready to merge. I initially thought I needed to change the backend, so I was looking into the server codebase.

2024-12-29 07:17 UTC, ptdatta commented
@skeptrunedev, will there be any start date for ' all time`?Like the date the dataset was created, or UNIX time 0?

2024-12-29 23:12 UTC, drew-harris commented
"all time" working properly, now doing the backend work to implement month granularity

2024-12-30 07:20 UTC, skeptrunedev submitted a review, later dismissed
Whenever I set the analytics to `all time`, I get backend server errors which shouldn't happen. 

Also, when the backend errors, the granularity on the chart visualization doesn't change.

![image](https://github.com/user-attachments/assets/05a2596e-c215-4205-8fa0-af4b659ddb9c)

![image](https://github.com/user-attachments/assets/ba2819cd-71b3-4224-978a-a1c613d01afd)

2024-12-30 23:24 UTC, drew-harris commented
Closing PR as we are running into issues grouping by month using the clickhouse rust crate. Reopening as draft so that @densumesh can take a look at whats going on with rust crate before we proceed. Thank you @ptdatta for your work!

2025-01-01 21:11 UTC, drew-harris commented
https://github.com/user-attachments/assets/874a5e04-a059-435a-93ae-b29b170363b9

2025-01-01 22:09 UTC, cdxker approved these changes

2025-01-01 22:10 UTC, merged