feature: moved to ingestion microservice
devflowinc/trieve pull request #892
Opened 2024-01-30 09:22 UTC by densumesh

## Please indicate what issue this PR is related to and @ any maintainers who are relevant

2024-01-30 17:20 UTC, skeptrunedev requested changes
looks good beyond the one print, has this been tested?

2024-01-30 17:20 UTC, skeptrunedev commented on embedding-server/embeddings.py
> +    print(doc_scores)
```suggestion
```

should remove the print

2024-01-31 00:48 UTC, fastfists approved these changes

2024-01-31 00:57 UTC, fastfists commented
Do not merge yet, Will add in Dockerfile as well

2024-01-31 18:16 UTC, skeptrunedev approved these changes

2024-01-31 19:58 UTC, merged